web:
    build: .
    ports:
        - "3000:3000"
    volumes:
        - .:/src
    links:
        - redis
        - postgres
    entrypoint: /bin/bash
    tty: true
redis:
  image: redis:latest
postgres:
  image: postgres:latest
