web:
    volumes:
        - .:/src
    entrypoint: /bin/bash
    tty: true
    extends:
        file: common.yml
        service: web
    links:
        - redis
        - postgres
redis:
  image: redis:latest
postgres:
  image: postgres:latest
